= Gantt: Clojure wrapper for PlantUML 
:git:               https://git-scm.com[git]
:clojure-deps-cli:  https://clojure.org/guides/getting_started[clojure deps cli]
:clj-new:           https://github.com/seancorfield/clj-new[clj-new]
:just:              https://github.com/casey/just[just]
:babashka:          https://github.com/babashka/babashka[babashka]
:source-highlighter: highlight.js
:toc:

image:doc/programming-clojure-plan.edn.svg[Demo plan]

== Intro

Program `gantt` transforms: `EDN -> SVG/PNG` without any external dependencies.

To produce the picture above the following command was used:

[source,bash]
----
java -Duser.language=en -jar gantt-0.1.0-SNAPSHOT-standalone.jar -f svg -i ./doc -o :input-folder generate
----

Click here to see link:doc/programming-clojure-plan.edn[EDN source] for the picture above using link:https://github.com/edn-format/edn[EDN format]. +
Click here to see intermediate link:doc/programming-clojure-plan.edn.puml[PUML file]  produced from EDN.  +

== Download

Download latest version of `gantt` program: link:https://github.com/redstarssystems/gantt/releases/[] 

== Build this project

Project `gantt` generated from https://github.com/redstarssystems/rssysapp[Application template].

=== Install project prerequisites

All these tools you need to install only once.

. Install {clojure-deps-cli} tools
.. MacOS
+
[source,bash]
----
brew install clojure/tools/clojure
----

.. Linux
+
Ensure that the following dependencies are installed in OS: `bash`, `curl`, `rlwrap`, and `Java`.
+
[source,bash]
----
curl -O https://download.clojure.org/install/linux-install-1.10.3.822.sh
chmod +x linux-install-1.10.3.822.sh
sudo ./linux-install-1.10.3.822.sh
----

. Install latest {clj-new} library to a file `~/.clojure/deps.edn`
+
[source,clojure]
----
{
 :aliases {
           :new     {:extra-deps {seancorfield/clj-new {:mvn/version "1.1.297"}}
                     :exec-fn    clj-new/create}
          }
 }
----

. Install {babashka}
.. MacOS
+
[source,bash]
----
brew install borkdude/brew/babashka
----
+
.. Linux
+
[source,bash]
----
sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
----

. Run once:
+
[source,bash]
----
just requirements
----

to install other necessary tools (MacOS only, for Linux manual instruction).

=== Project workflow

To configure project workflow scripts use `bb.edn`.

To configure project version use file `project-version`.

To configure `group-id` and `artifact-id` for jar file use file `project-config`.

To configure secrets & passwords use file `project-secrets.edn`.

Run `bb tasks` to show help for project workflow.

List of available tasks:

[sources]
----
clean        Clean target folder
build        Build application for this project (standalone uberjar file)
install      Install application uberjar file locally (requires the pom.xml file)
deploy       Deploy this application
run          Run application
repl         Run Clojure repl
outdated     Check for outdated dependencies
bump         Bump version artifact in `project-version` file, level may be one of: major, minor, patch, alpha, beta, rc, release.
test         Run tests
format       Format source code
lint         Lint source code
javac        Compile java sources (if any)
jar          Build thin jar file for this application
standalone   Create a standalone application with bundled JDK (using jlink, JDK 9+)
requirements Install project requirements
----

=== License

This work is dual-licensed under Eclipse Public License 2.0 and GPL 3.0. +
PlantUML and java sources in  `java/src` are under GPL 3.0. (C) Copyright 2009-2020, Arnaud Roques + 

Rest of the program is under EPL 2.0. Copyright © 2021 Mikhail Ananev +
You can choose between one of them if you use this work. +

`SPDX-License-Identifier: EPL-2.0 AND GPL-3.0-or-later`


