@startgantt

Project starts 2021-05-27

scale 320*280

projectscale daily


[Task1] as [t1] lasts 6 days and starts 2021-05-28
[Task2] as [t2] lasts 8 days and starts at [t1]'s end

[t1] is 20% completed
[t2] is 20% completed



@endgantt